// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "DiskusiTugas/domain"

	mock "github.com/stretchr/testify/mock"
)

// QuestionRepository is an autogenerated mock type for the QuestionRepository type
type QuestionRepository struct {
	mock.Mock
}

// Destroy provides a mock function with given fields: id
func (_m *QuestionRepository) Destroy(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchQuestionBySubject provides a mock function with given fields: idSubject, page, pageSize
func (_m *QuestionRepository) FetchQuestionBySubject(idSubject int, page int, pageSize int) ([]domain.Question, int, error) {
	ret := _m.Called(idSubject, page, pageSize)

	var r0 []domain.Question
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, int) ([]domain.Question, int, error)); ok {
		return rf(idSubject, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) []domain.Question); ok {
		r0 = rf(idSubject, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) int); ok {
		r1 = rf(idSubject, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int, int) error); ok {
		r2 = rf(idSubject, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FetchWithPagination provides a mock function with given fields: page, pageSize
func (_m *QuestionRepository) FetchWithPagination(page int, pageSize int) ([]domain.Question, int, error) {
	ret := _m.Called(page, pageSize)

	var r0 []domain.Question
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]domain.Question, int, error)); ok {
		return rf(page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(int, int) []domain.Question); ok {
		r0 = rf(page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int); ok {
		r1 = rf(page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: id
func (_m *QuestionRepository) GetByID(id int) (domain.Question, error) {
	ret := _m.Called(id)

	var r0 domain.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (domain.Question, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) domain.Question); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Question)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDQuestion provides a mock function with given fields: id
func (_m *QuestionRepository) GetByIDQuestion(id int) (domain.Question, error) {
	ret := _m.Called(id)

	var r0 domain.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (domain.Question, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) domain.Question); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Question)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIdSubject provides a mock function with given fields: slug
func (_m *QuestionRepository) GetIdSubject(slug string) uint {
	ret := _m.Called(slug)

	var r0 uint
	if rf, ok := ret.Get(0).(func(string) uint); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// Store provides a mock function with given fields: question
func (_m *QuestionRepository) Store(question *domain.Question) error {
	ret := _m.Called(question)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Question) error); ok {
		r0 = rf(question)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: id, question
func (_m *QuestionRepository) Update(id int, question *domain.Question) error {
	ret := _m.Called(id, question)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *domain.Question) error); ok {
		r0 = rf(id, question)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuestionRepository creates a new instance of QuestionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestionRepository {
	mock := &QuestionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
