name: Docker Image CI

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/miniprojek:latest
      -  
        name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST_IP_GCP }}
          username: ${{ secrets.USERNAME_GCP }}
          key: ${{ secrets.KEY_SSH_GCP }}
          port: ${{ secrets.PORT_GCP }}
          script: |
            docker stop ${{ secrets.COINTAINER_NAME }}
            docker rm ${{ secrets.COINTAINER_NAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/imgkmb
            docker run --name ${{ secrets.COINTAINER_NAME }} --rm -it -p 8000:8000 -d ${{ secrets.DOCKERHUB_USERNAME }}/miniprojek
